# Main vars which should be included in files
$mainMod = SUPER
$terminal = foot
$fileManager = dolphin

# X11 SETTINGS
# Flicekering fix for Intellij Idea which blocks X11 usage
env = _JAVA_AWT_WM_NONREPARENTING,1

# WINDOW RULES
# Windows rule to make experience in jetbrain products smoother
# Turning off animations which can be spawned (shadows, etc...)
windowrule {
    name = jetbrains-popups
    match:class = ^(jetbrains-.*)$
    match:title = ^(win.*)$
    no_anim = on
    no_initial_focus = on
}

# For small menus on diffrent part of the screen (deprecated)
