# BINDS WHICH OVERRDING CAELESTIA'S 
bind = $mainMod, Return, exec, $terminal # SUPER + ENTER = TERMINAL (foot)
bind = $mainMod, E, exec, $fileManager # SUPER + ENTER = FILE MANAGER (dolphin)

animations {
    enabled = yes

    # Custom Bezier curve for a snappy, responsive feel
    # Format: x0, y0, x1, y1 (Cubic Bezier points)
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    # Window animations: 
    # Speed set to 3 for fast opening/closing
    animation = windows, 1, 3, myBezier
    animation = windowsOut, 1, 3, default, popin 80%
    
    # Border & Fade:
    # Keeps UI transitions subtle but quick
    animation = border, 1, 5, default
    animation = fade, 1, 3, default

    # Workspace switching:
    # Speed 2 + slide effect makes desktop hopping ultra-fast
    animation = workspaces, 1, 2, myBezier, slide
}

input {
    # List of layouts
    kb_layout = us,ru,it,ua
    
    # Switch wich Alt+Shift
    kb_options = grp:alt_shift_toggle
    
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 1.5  # Та самая скорость скролла, которую мы обсуждали
    }
}

# AUTOSTART
